//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreeningReports.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        [Required(ErrorMessage = "UserName field is Required")]
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password field is Required")]
        public string Password { get; set; }
        public System.DateTime RegnDate { get; set; }
        public int RegnNo { get; set; }
        public string SampleType { get; set; }
        public System.DateTime SampleDate { get; set; }
        public string RegnCenter { get; set; }
        public string RegnState { get; set; }
        public string RegnCountry { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PhoneNo { get; set; }
        public string PassportNo { get; set; }
        public string TestResult { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public string SCPassportErrorMessage { set; get; }
        public string SCResultError { set; get; }
        public string LogInErrorMessage { set; get; }
        public string PassportErrorMessage { set; get; }

    }
}
